### ISSUE TITLE
Change hook location of activation border

### ISSUE THREAD

**Issue by Jalopyy** [ascott18/TellMeWhen#16]
I'm not 100% sure if this is even possible. Right now the activation border default hooks on the inside of the aura. Would be nice if there was a way to hook it to the icon border, or a way to artificially increase the size of the activation border so it can be manually set as big around the icon as I want.

I assume this isn't possible since it's probably a Blizzard controlled area where the shine is spawned.

**Comment by ascott18** [comment]
It isn't really hooked to anything, per-se. Its more just placed in the middle of the icon and sits there floating on top of it, at the mercy of whatever size Blizzard decided it should be. It didn't used to be like this, because the code in TMW does try to deliberately size it, but it looks like at some point, Blizzard made a change and the code in TMW that tries to set the size of it has no effect.

So, I added a scale setting that you can configure in 6a5dc8ae.
