### ISSUE TITLE
Icon cooldown and power check, icon show instead cooldown not ready

### ISSUE THREAD

**Issue by AcidAmer** [ascott18/TellMeWhen#1679]
Hello,

I have an icon (spell) that i want to show when the cooldown is ready and to show with 70 % opacity if not enough power to cast it.

So i set this icon with "spell cooldown" and i checked "power check"

The problem is that when the cooldown isn't ready and i don't get enough power, the icon show at 70 % opacity.

It look likes the addon  give the priority to "power check", if power is not enough the icon just show at his setting value and don't care about the cooldown.

Is there a way that 

**if cooldown not ready and not enough power : icon don't show**
if cooldown not ready : icon don't show
if cooldown ready and not enough power : icon show at 70 % opacity
if cooldown ready and enough power : icon show (at 100 % opacity)

**What are you trying to accomplish?**

Thank's for your add on :)

Acid

**Comment by ascott18** [comment]
You can use conditions for this instead of the Power Check setting.
- Set the not ready opacity to 0%/hidden
- Set the ready opacity to 100%
- Add two conditions to the icon: 
  - Spell Cooldown of your spell > 0 (ready) 
  - OR Spell Usable (Mana/Energy/etc.) of your spell == true 
- Set the condition failed opacity to 70%

This will cause the conditions to pass when the spell is on CD (so the "not ready" opacity will be used), or when the spell has mana (so the "ready" opacity will be used). In the case of the spell is ready and mana is insufficient, the conditions will fail, causing the condition failed opacity to be used.

**Comment by AcidAmer** [comment]
It works perfectly, thank you :)
