### ISSUE TITLE
[Bug] does not display the cooldown of the second ability if Spell ID is entered instead of names

### ISSUE THREAD

**Issue by turubanov** [ascott18/TellMeWhen#1691]
**What version of TellMeWhen are you using? **

8.6.0

**What steps will reproduce the problem?**
1. Create Spell Cooldown icon.
2. In the field "What to track" enter 2 Spell ID (e. g. 262161; 167105)
3. 

**What do you expect to happen? What happens instead?**
If you enter the names of abilities - the icon works

**Screenshots and Export Strings**

^1^T^SShowTimer^B ^SType^Scooldown ^SShowTimerText^B ^SName^S262161;~`167105 ^SShowTimerTextnoOCC^B ^SClockGCD^B ^SStates^T ^N2^T ^SAlpha^N0.5 ^t^t^SRangeCheck^B ^SEnabled^B ^t^N86006^S~`~| ^Sicon^^

**Additional Info**

**Comment by ascott18** [comment]
Working as intended. TMW (and WoW) looks up spell names from your current spellbook. If you don't have the spell, it effectively doesn't exist - it will behave the same way as entering a spellid that doesn't exist. However, when a spellID is entered, TMW will stop and display that specific ID because it has know way of knowing if that's something that it should or should not check. There are lots of cooldowns you can check by ID that aren't actually spells that your class owns - battle rez, for example, can always be checked from any class if you check it by ID - doing so will display your raid's shared BR cooldown.
