### ISSUE TITLE
[Wrong Timer] Vision of Perfection Wrong Timers On Procs

### ISSUE THREAD

**Issue by v-radev90** [ascott18/TellMeWhen#1708]
For warlocks Vision of Perfection Major Essence (Tested on Rank 3) has a chance to summon your major Guardian (Infernal, Darkglare or Demonic Tyrant) for 35% of its base duration. However when the proc happens the duration on the icon's timer shows 100% uptime (30sec) and not the real 35% (10.5sec) and even when the guardian disappears the timer keeps going to 0 even though there is no guardian present. This issue is present in the Guardians Icon Option.

**Comment by ascott18** [comment]
This will be difficult to fix, since I don't know if the short-duration summon uses any different spellIDs than a regular summon. If it doesn't, then I don't think there's anything I can do because the summon will be indistinguishable by addons.

I also don't have a warlock that I could test this with.

**Comment by ascott18** [comment]
One thing you could try for me is to install the addon idTip (https://www.curseforge.com/wow/addons/idtip), then look at your combat log for when this proc happens and look for a line like:
```
19:13:15> [Your] [Summon Infernal] summoned [Infernal].
```

When it happens, hover over the `[Summon Infernal]` link and tell me what ID it displays in the tooltip.
