### ISSUE TITLE
[Bug] Classic : Power word: Fortitude

### ISSUE THREAD

**Issue by guischmo** [ascott18/TellMeWhen#1739]
**What version of TellMeWhen are you using? **
v8.6.8 Classsic

**What steps will reproduce the problem?**
I'm trying to watch my "Power Word: Fortitude" spell buff with my priest.
I'm using the french wow client so the spell name is "Mot de pouvoir : Robustesse"

The client find the spell in the suggestion list but then when i select it it doesnt work (there is a stopwatch icon displaying insted)

I also tried with the spell id "1255", then the icon is correct but  it still doesn't work as the buff is still not being watched by TMW.

Maybe this has to do with the special caracter ":" in the spell name ?

**Comment by ascott18** [comment]
It could be because of the space before the colon in the name.

If you want to track by ID, you'll need to include the ID of every rank. Additionally, 1255 is not an ID of any rank that is available to players. You can see the ranks that are available to players by typing in the name and looking at the suggestion list - player spells have a pink background:

![image](https://user-images.githubusercontent.com/5017521/65836120-bd995500-e2a3-11e9-9dff-5dd95ad2bfbc.png)

**Comment by guischmo** [comment]
Alright, I put all of them and it works , thanks a lot

**Comment by ascott18** [comment]
Using the name will also be fixed in the next version of TMW. Thanks for the report!
