### ISSUE TITLE
[Bug?] Set Group Point gets lost when moving a group

### ISSUE THREAD

**Issue by tflo** [ascott18/TellMeWhen#1811]
Maybe I‘m doing something wrong or it’s a quite simple UI flaw, but it is bothering me since ages:

When I move a group, which had a Group Point set, the set Group Point is lost after the moving. Have to set it again, otherwise my icons will appear on the other end, or centered or what not.

Not sure if this is WAD, but I can’t imagine. Because once a Group Point is set, it should stay until I reset it, and it should _not_ get cancelled by any movement to the group.

Well, once you know that TMW is behaving like this, you make it a habit to re-correct the Group Point every time you have moved something, so it is a minor issue. Nevertheless I think this shouldn’t be like that.

Thanks for this incredibly great add-on; prefer it ten times to WA.

– Tom

**Comment by ascott18** [comment]
@tflo Is this only really an issue only for groups using the "Shrink group" option? I don't necessarily want to change this for all groups all the time, as otherwise it would cause a suboptimal experience for all other groups when changing resolutions, changing UI scale, etc.

**Comment by tflo** [comment]
Yes, it’s an issue only with shrinking groups. (Sorry, forgot to mention this, because virtually all my groups that have more than one member are shrinking ones.)

**Comment by tflo** [comment]
Just asking, since some time has passed: 

Any news on a fix for this? Or is it a “won’t fix”?

I re-read your reply from Oct 18, and I don’t see how this could be related to changing resolutions or UI scale. 

This made me think that maybe it wasn’t clear what my point is (my English is not the best obviously):

The thing I’m complaining about is that when I’m “touching” a group (i.e. moving it, even if it’s only 1px), any set Group Point is lost and replaced by some (apparently) random Group Point I’ve never selected.

Some reasons why I consider this behavior buggy (or at least undesirable) are:

- There is an UI for setting the Group Point. If I wanted to change the Group Point I would use that.
- Changing a Group Point is rarely related to changing the position of the group on screen. For example, if I move my group, let’s say 20px to the left, to align it with some other group or UI element, I don’t see any benefit of getting my Group Point cancelled, which I’ve just selected five seconds before.
    - The only exception that occurs to me, where a position change would make a Group Point change desirable, is when the position change is a really major one: For example moving a group from the right edge of the screen to left one. But even then I would prefer to select a new Group point myself in the UI, instead of getting a forced change.
- In general, a setting should not be affected by any other unrelated setting change (unless for technical reasons). For example, once I’ve set the scaling of a group to 1.5, I would never want to see this auto-changed to something else when I move the group, or add a column/row, or whatnot. I’ve set it to 1.5 for a reason. The same for the Group Points.
- A Group Point is an integral and important setting of any Shrinking Group. If there are some (technical) reasons for a forced Group Point change when moving the group, then please consider excluding Shrinking Groups from that forced change _– if somehow possible_.

But – since this behavior has been there for years – I almost _feel_ that something important escapes me. If this is so, please enlighten me.

– Tom

**Comment by ascott18** [comment]
> I don’t see how this could be related to changing resolutions or UI scale.

The reason that the point is changed when clicking-and-dragging to move is so that the group maintains the "intent" of where you wanted it. If you create a group and drag it to the top left corner of the screen, the group point and target point are both set to the top left. This allows the group to remain in the top left where you put it even if your resolution, aspect ratio, or resolution changes. If you then click-and-drag this group to the top right of your screen, both settings are set to top-right. If this wasn't done, the group may end up off the edge of the screen, or otherwise in totally the wrong spot, when external factors are changed.

This behavior is so fundamental that it is implemented into the core of Blizzard's UI system. Any frame that you click-and-drag to move will do this by default unless specific custom code has been written to overcome this. TMW groups are no exception here. It just so happens that TMW groups, unlike the vast majority of other frames in your UI, have a UI that exposes these settings to you that otherwise would remain a small, internal implementation detail.

Hence my question about "shrink group" - I don't want to modify this behavior for all groups all the time because 99% of users aren't enabling Shrink Group - such groups and the users who created them will continue benefiting from not having any behavior changed.

If you don't want the position settings being updated when clicking-and-dragging, you can disable clicking and dragging by enabling "Lock Position" to prevent accidental clicking-and-dragging.

> then please consider excluding Shrinking Groups from that forced change – if somehow possible.

Yes, that was the whole reason I asked you that question in the first place.

**Comment by tflo** [comment]
Many thanks for the new version! Much better now 😊
