### ISSUE TITLE
[Bug] DogTag invalid key to "next"

### ISSUE THREAD

**Issue by cordankos** [ascott18/TellMeWhen#1886]
**What version of TellMeWhen are you using? **
Latest from curseforge v9.0.6

**What steps will reproduce the problem?**
1. Just play Battleground 
2. Happens randomly in fights

**Screenshot of error**
https://imgur.com/ZDwMPYA

**Additional Info**
I don't use these DogTags for units but error still happen, I noticed this on the latest version of TMW, I didn't used previous few versions so idk if this error happened earlier.

**Comment by Zardilann** [comment]
I only started experiencing this recently, it pops up in dungeons mainly.

**Comment by Neo-The-Wan** [comment]
Hello,

Normally a fix, to test, already exists in the new version of the LibDogTag-Unit-3.0 library, but this one is not yet included in TellMeWhen 9.0.6.

You can wait for a new version of TellMeWhen, or in the meantime, try to manually replace the version of LibDogTag-Unit-3.0, included in TellMeWhen, with the latest available:

https://github.com/parnic/LibDogTag-Unit-3.0/releases/download/v90000.5/LibDogTag-Unit-3.0-v90000.5.zip

**Comment by alsiniz** [comment]
Just want to bump this and say that I've been experiencing this for months. 

It was driving me mad because I didn't figure out that TMW was the source until I installed buggrabber/bugsack which gave me a more detailed LUA error. I can't figure out what triggers it but it happens to my all the time in dungeons and raids.

**Comment by alsiniz** [comment]
Here's a print out from buggrabber. I couldn't copy/paste the text since I was in combat but I was able to pull up the error after combat for reference. Sorry that it's a screenshot and not a text submission.

![image](https://user-images.githubusercontent.com/61495022/115167627-5df2dc80-a0c9-11eb-8f9a-26f72e00fa32.png)

**Comment by alsiniz** [comment]
> 
> 
> Hello,
> 
> Normally a fix, to test, already exists in the new version of the LibDogTag-Unit-3.0 library, but this one is not yet included in TellMeWhen v9.0.6.
> 
> You can wait for a new version of TellMeWhen, or in the meantime, try to manually replace the version of LibDogTag-Unit-3.0, included in TellMeWhen, with the latest available:
> 
> https://github.com/parnic/LibDogTag-Unit-3.0/releases/download/v90000.5/LibDogTag-Unit-3.0-v90000.5.zip

Thank you for this. I've replaced my LibDogTag-Unit library in the TMW directory. I hope this works!

**Comment by Zardilann** [comment]
I haven't experienced the bug after replacing the library a week ago.

**Comment by ascott18** [comment]
9.0.7 has been released that includes the latest LDT-Unit
