### ISSUE TITLE
[Feature Request] Add Ability to Add Dispel Types and Debuff Equivalencies As Conditions

### ISSUE THREAD

**Issue by StreetLight777** [ascott18/TellMeWhen#1904]
The title says it all. While the addon currently allows the tracking of Dispel Types and/or Debuff Equivalencies (e.g. Magic, Poison), it is not possible to add this as a Condition in another icon type - only specific spell IDs are available when using the Debuff Duration.

It would be SUUUPER handy if you can add Dispell Types and/or Debuff Equivalencies in the conditions - either as trigger conditions or as notification conditions.

Use Case: I want to setup an Activation Border Notification / Animation for my Mass Dispel ability when:
Group Type = Solo AND 
**Player has a Magic debuff type present AND**
Purify spell is on cooldown

At present, the condition in bold is not possible as tmw asks for specific spells in the Conditions sub menu. 

The only 'work around' for this is to just create a 2nd icon 'on top of' the existing icon that is setup as the Buff/Debuff type, which is the only way to use Dispel Types and/or Debuff Equivalencies as far as I'm aware. This work-around is clunky and requires a lot more effort to setup.

**Comment by Alwies** [comment]
Hey, Just wanna let you know of another easier workaround.
Create the buff/debuff icon to detect your **bold condition** and use that icon as a condition through Misc > icon is shown.
Said icon doesn't have to be visible, for example, you could enable always hide.

**Comment by ascott18** [comment]
An Icon Is Shown condition has always been the proper solution to this as @Alwies mentioned. 

Delegating heavy buff/debuff checking to an icon has a number of performance benefits over including it within a chain of conditions. This is because the individual components of a set of conditions are not cached, so when any event triggers the condition to be re-evaluated, the whole thing has to be re-evaluated.
