### ISSUE TITLE
[Feature request]: Interruptable spell cast in TBCC

### ISSUE THREAD

**Issue by relaxedSoul** [ascott18/TellMeWhen#1937]
# Issue
On WoW TBC Classic the following is not possible: 
Create a condition item, where I select `Spell cast` and select a checkbox `interruptable` as this checkbox doesn't exist.

I am using version 9.2.2, found in the network that already in 9.0.2 there is a third option together with "Present" and "Not Present" (not sure how they are called I have a localization).

# Thoughts
## Where it works
The addon `neatplates`, or probably every addon showing the casts of the target, focus, or anyone, can show that the spell is interruptable or not (changing the color of the cast bar).

## How I suppose it can work
It brings me a question if the API exists but is not used in TMW. 

## Or maybe durty way
I understand, that probably the property "interruptable" can come together with the huge list of spell IDs collected from somewhere, so the addon knows if the spell is interruptable by its ID and (if it matters) the name of the caster.

**Comment by ascott18** [comment]
This is not possible because the game API does not return this info. Other addons may be approximating this by, as you mentioned, maintaining huge lists of spells and probably also any buffs that might make someone immune to interrupt.

For the specific addon example you gave of Neatplates, the described functionality does not actually work. It specifically has code to treat all casts in TBC and Vanilla as interruptible because again, this information is not available in the game API.
![image](https://user-images.githubusercontent.com/5017521/170627040-d6b23bdf-62fc-4d1c-ab73-3a41ff725589.png)

**Comment by relaxedSoul** [comment]
@ascott18 thank you for the detailed answer!
