### ISSUE TITLE
Bug: Ghoul tracker icon blings when the ghoul despawns

### ISSUE THREAD

**Issue by AddonWhiner** [ascott18/TellMeWhen#2019]
### WoW Version

Retail

### TellMeWhen Version

10.0.2

### Describe the bug

I have this icon:

![image](https://user-images.githubusercontent.com/110006730/203622086-0545f7c2-c288-4a25-8166-b5b253e6919e.png)

It is used for a meta icon. The bar is hidden (and I've set the icon itself to Always Hide to no avail). The issue is that when my ghoul despawns, I get this bling effect in the same place as that icon:

![image](https://user-images.githubusercontent.com/110006730/203622695-fee01edd-fa07-4ae5-91eb-20a6f8581e43.png)

Disable Blizzard cooldown finish pulse was already checked, so that didn't help either. Anyway, this happens for no other icon, not even the visible ones. Alwies and I theorize that it may have to do with the ghoul technically being a totem. For clarity, I am having this issue as Blood. I don't know what happens for the other specs.

### Export Strings

```text
^1^T^SShowTimer^B ^SUnit^S ^SType^Stotem ^SSourceUnit^Splayer ^SCLEUDur^N60 ^SName^SRaise~`Dead ^SGUID^STMW:icon:1X3C4wSyJcuY ^SShowTimerTextnoOCC^B ^SCLEUEvents^T ^SSPELL_CAST_SUCCESS^B ^t^SFakeHidden^B ^SOnlyIfCounting^B ^SEnabled^B ^t^N100200^S~`~| ^Sicon^^
```

**Comment by ascott18** [comment]
Yeah, its because the totem API in wow is one of the oldest and worst things in wow addon dev. Most things that expire will go away as soon as they expire (e.g. a cooldown is ready the moment it finishes, so a cooldown icon that's hidden when the ability is ready will never show the flash).

This is not the case for totems. Totems keep existing for a short while after their timer ends.

I'll just change the icon type to immediately treat an expired totem as gone, even though it technically keeps existing for a short while after. I guess if people end up not liking that, I can add that behavior as a setting.
