### ISSUE TITLE
not loading all icons after release

### ISSUE THREAD

**Issue by VasiliySharov** [ascott18/TellMeWhen#2043]
### WoW Version

Retail

### TellMeWhen Version

10.0.5

### Describe the bug

my set of icons not loading completely especially in arena and bgs. first log in game and enter/exit tmw settings via /tmw helps to fix it but as long as I'm in arena it loads 20% of all my icons. I tried to turn off all addons except tmw and it didn't work out

### Export Strings

```text
N/A
```

**Comment by Alwies** [comment]
Hey, not Cybeloras so take this as you will. 

The bug you're describing sounds very familiar to one that happens when using an out of date TMW version.
Curseforge can under some circumstances show a "modified" descriptor instead of the update button. Which can (and has) easily been interpreted as having the most recent version when in fact you don't. 

If I'm in the wrong apologies and thanks for considering.

**Comment by ascott18** [comment]
Indeed, sounds like you're using an old version. If that's not it, please add an export string of your entire profile.

**Comment by VasiliySharov** [comment]
it seems I fixed it. the name of the button "QueueStatusButton" was changed, I had it in conditions, and it failed all my setting to load
