### ISSUE TITLE
Combat Events not filtering when only a Destination Unit is defined

### ISSUE THREAD

**Issue by geckzilla** [ascott18/TellMeWhen#2098]
### WoW Version

Retail

### TellMeWhen Version

10.1.5

### Describe the bug

This was meant to output a string indicating what was cast on [player] to the chat window. If I sit in Valdrakken, though, I get spammed with anything anyone casts that doesn't have a destination defined. 

### Export Strings

```text
^1^T^SUnit^Snameplate~`1-40 ^SCLEUEvents^T ^SSPELL_CAST_SUCCESS^B ^t^SType^Scleu ^SUnitConditions^T ^N1^T ^SType^SREACT ^SLevel^N1 ^t^N2^T ^SType^STHREATRAW ^t^Sn^N2 ^t^SEvents^T ^N1^T ^SType^SAnnouncements ^SChannel^SFRAME ^SLocation^SGeneral ^SText^S[Spell]~`=>~`[Destination:Name] ^SEvent^SOnCLEUEvent ^t^Sn^N1 ^t^SSettingsPerView^T ^Sicon^T ^STextLayout^STMW:textlayout:1ZhzkpYM_fGU ^STexts^T ^N1^S ^t^t^t^SDestUnit^Splayer ^SEnabled^B ^t^N101500^S~`~| ^Sicon^^

^1 ^T^N1^T ^SAnchors^T ^N1^T ^Sy^N-4 ^Sx^N-4 ^Spoint^STOPRIGHT ^SrelativePoint^STOPRIGHT ^t^t^SJustifyV^STOP ^SWidth^N24 ^SStringName^SNumber ^SName^SLiberation~`Sans~`(U) ^SConstrainWidth^b ^SOutline^SOUTLINE ^SSize^N6 ^t^SGUID^STMW:textlayout:1ZhzkpYM_fGU ^SName^SCenter~`Info~`Text ^t^N101500^S~`~| ^Stextlayout^STMW:textlayout:1ZhzkpYM_fGU ^^
```

**Comment by ascott18** [comment]
This is intentional, although I'll agree that its a bit confusing. Some events (like SPELL_CAST_SUCCESS) sometimes have a unit, and sometimes don't. In order to support icons that are tracking multiple different events where some have units and some don't, unit filtering by unitID isn't applied to events that have no unit.

You can configure the icon to ignore events where the event has no destination unit:
![image](https://github.com/ascott18/TellMeWhen/assets/5017521/330b454e-f8db-44ac-a18d-bc1553a7bd70)
