### ISSUE TITLE
Slice and Dice duration incorrect

### ISSUE THREAD

**Issue by LeCampy** [ascott18/TellMeWhen#2144]
### WoW Version

Retail

### TellMeWhen Version

10.2.2

### Describe the bug

Tracking Buff/Debuff Slice and Dice  (either id 315496 or 344362) with Show Timer and Show Timer text, targetting player will set the duration to 2h when the initial start timer is over 60 seconds, and will not countdown  properly; sometimes it counts down once it goes below 50 seconds, sometimes it stays at 2h for the full duration until the buff falls off

![WoWScrnShot_011524_110307](https://github.com/ascott18/TellMeWhen/assets/156709607/f06b1f4f-928a-4e69-af10-4eb79eed8d08)

### Export Strings

```text
^1^T^SShowTimer^B ^SType^Sbuff ^SShowTimerText^B ^SName^SSlice~`and~`Dice ^SEnabled^B ^t^N102201^S~`~| ^Sicon^^
```

**Comment by Alwies** [comment]
Had a chat with someone about this on discord a while back. 
The talent "Underhanded Upper Hand" [Image](https://cdn.discordapp.com/attachments/546942554038468608/1189641395271651359/image.png?ex=65b15be3&is=659ee6e3&hm=84900308c344cbc6561b91731820b4cb27b87ba406180f3ef7b25f1b96e1a1b5&) will freeze the duration during blade flurry, the actual implementation in the API however is just multiple the remaining time by 100. Which is why it displays 2 hours. 

Now where there may be a bug is that it should revert to normal duration outside of flurry and shouldn't fall off unless the timer hits 0. Assuming there's no rogue mechanic that removes it. 
Now what can happen if you "freeze" it with a few seconds remaining it'll go to a big number again but when unfrozen disappear very fast.

**Comment by LeCampy** [comment]
Should have known it was the redesign, the timing lines up.

And I have to amend my previous account, there's no bug then, it's reverting back to normal countdown when BF falls off. 

The problem is that BF should not fall off at least in dungeons, so I wasn't seeing the pattern. If the display issue with Underhanded Upper Hand is a "Broken as Designed", because of Blizz code, I def can live with that.
