### ISSUE TITLE
Add a condition to the Spell Cooldown icon to track if the spell is usuable

### ISSUE THREAD

**Issue by RealHawkBat** [ascott18/TellMeWhen#2211]
**Is your feature request related to a problem? Please describe.**
Spells where using the spell turns it into another spell (e.g. "Sacred Weapon" turning into "Holy Bulwark") cannot be properly managed in TellMeWhen. If as part of your rotation, different conditions need to be met to use one spell or the other, there is no way to manage this if TellMeWhen treats them as the same spell.

**Describe the solution you'd like**
Add a condition to the Spell Cooldown icon to track if the spell is usuable. After a discussion with a mod on the discord, it was suggested that adding "C_Spell.IsSpellUsable" as a condition could be the solution.

**Describe alternatives you've considered**
I've tried using the "Spell Learned" condition, but it doesn't work in this scenario. I've tried tracking via the spellids, but TellMeWhen still seems to consider them the same spell.

**Additional context**
I initially raised this as a bug here: https://github.com/ascott18/TellMeWhen/issues/2207
However, as the response was that it is working as intended, I thought raising it as a feature request would be the next step, as this would be impacting any users that have these kinds of spells in the rotation.

**Comment by ascott18** [comment]
Your original issue did not describe any nuance - just a desire that **all** replacement spells should cease following the current active override. This would do nothing beneficial and would only make shadow priests **very** angry.

What you're asking for already exists - use the Spell Learned condition to check Sacred Weapon. Don't use it on Holy Bulwark since that's the "base" spell and is always learned (as you can see from the icon of the talent and the fact that it only says "replaced by..." when Sacred Weapon is active)

![image](https://github.com/user-attachments/assets/912fcbaf-9873-4470-9826-ab66a92c54c1)
